"""OpenSolve Pipe data models.

This module provides Pydantic models for all core data structures used in
OpenSolve Pipe hydraulic network analysis.
"""

from .base import (
    Diameter,
    Elevation,
    Flow,
    Head,
    Length,
    NonNegativeFloat,
    NonNegativeInt,
    OpenSolvePipeBaseModel,
    PositiveFloat,
    PositiveInt,
    Pressure,
    Temperature,
    Velocity,
)
from .branch import (
    BaseBranch,
    Branch,
    BranchType,
    CrossBranch,
    TeeBranch,
    WyeBranch,
    create_cross_ports,
    create_tee_ports,
    create_wye_ports,
)
from .components import (
    BaseComponent,
    Component,
    ComponentType,
    Connection,
    HeatExchanger,
    Junction,
    Orifice,
    PumpComponent,
    PumpOperatingMode,
    PumpStatus,
    Reservoir,
    Sprinkler,
    Strainer,
    Tank,
    ValveComponent,
    ValveStatus,
    ValveType,
)
from .connections import (
    ConnectionBuilder,
    PipeConnection,
    validate_connection,
    validate_port_direction_compatibility,
    validate_port_size_compatibility,
)
from .fluids import FluidDefinition, FluidProperties, FluidType
from .piping import (
    Fitting,
    FittingType,
    PipeDefinition,
    PipeMaterial,
    PipeSchedule,
    PipingSegment,
)
from .plug import Plug, create_plug_port
from .ports import (
    Port,
    PortDirection,
    create_heat_exchanger_ports,
    create_junction_ports,
    create_orifice_ports,
    create_pump_ports,
    create_reservoir_ports,
    create_sprinkler_ports,
    create_strainer_ports,
    create_tank_ports,
    create_valve_ports,
)
from .project import Project, ProjectMetadata, ProjectSettings
from .pump import FlowEfficiencyPoint, FlowHeadPoint, NPSHRPoint, PumpCurve
from .reference_node import (
    BaseReferenceNode,
    FlowPressurePoint,
    IdealReferenceNode,
    NonIdealReferenceNode,
    ReferenceNode,
    ReferenceType,
    create_reference_node_port,
)
from .results import (
    ComponentResult,
    FlowRegime,
    PipingResult,
    PumpResult,
    SolvedState,
    Warning,
    WarningCategory,
    WarningSeverity,
)
from .units import SolverOptions, UnitPreferences, UnitSystem

__all__ = [
    "BaseBranch",
    "BaseComponent",
    "BaseReferenceNode",
    "Branch",
    "BranchType",
    "Component",
    "ComponentResult",
    "ComponentType",
    "Connection",
    "ConnectionBuilder",
    "CrossBranch",
    "Diameter",
    "Elevation",
    "Fitting",
    "FittingType",
    "Flow",
    "FlowEfficiencyPoint",
    "FlowHeadPoint",
    "FlowPressurePoint",
    "FlowRegime",
    "FluidDefinition",
    "FluidProperties",
    "FluidType",
    "Head",
    "HeatExchanger",
    "IdealReferenceNode",
    "Junction",
    "Length",
    "NPSHRPoint",
    "NonIdealReferenceNode",
    "NonNegativeFloat",
    "NonNegativeInt",
    "OpenSolvePipeBaseModel",
    "Orifice",
    "PipeConnection",
    "PipeDefinition",
    "PipeMaterial",
    "PipeSchedule",
    "PipingResult",
    "PipingSegment",
    "Plug",
    "Port",
    "PortDirection",
    "PositiveFloat",
    "PositiveInt",
    "Pressure",
    "Project",
    "ProjectMetadata",
    "ProjectSettings",
    "PumpComponent",
    "PumpCurve",
    "PumpOperatingMode",
    "PumpResult",
    "PumpStatus",
    "ReferenceNode",
    "ReferenceType",
    "Reservoir",
    "SolvedState",
    "SolverOptions",
    "Sprinkler",
    "Strainer",
    "Tank",
    "TeeBranch",
    "Temperature",
    "UnitPreferences",
    "UnitSystem",
    "ValveComponent",
    "ValveStatus",
    "ValveType",
    "Velocity",
    "Warning",
    "WarningCategory",
    "WarningSeverity",
    "WyeBranch",
    "create_cross_ports",
    "create_heat_exchanger_ports",
    "create_junction_ports",
    "create_orifice_ports",
    "create_plug_port",
    "create_pump_ports",
    "create_reference_node_port",
    "create_reservoir_ports",
    "create_sprinkler_ports",
    "create_strainer_ports",
    "create_tank_ports",
    "create_tee_ports",
    "create_valve_ports",
    "create_wye_ports",
    "validate_connection",
    "validate_port_direction_compatibility",
    "validate_port_size_compatibility",
]

# Rebuild models with forward references now that all models are defined
PipeConnection.model_rebuild()
Project.model_rebuild()

MODEL_VERSION = "1.0.0"
